### ISSUE TITLE
USB class indendification provided by hwinfo/kernel is insufficient

### ISSUE THREAD

**Issue by Mic92** [numtide/nixos-facter#117]
nixos-facter cannot classify the usb dongle in framework 16 as bluetooth device: https://codeberg.org/jopejoe1/nix-conf/src/branch/main/systems/omoikane/facter.json

Lsusb also exposes interface descriptors that have these information: https://pad.missing.ninja/480XKviWSgiYcsWa76Fx_w?view=#

Sysfs is not sufficient: https://pad.missing.ninja/GE_ThvWXT-ywVfebJitFiQ#
Lsusb uses libusb in userpace to dump this information. 
On the first look it seems easier to parse lsusb output because it also encodes internally
a lot of information beyond the library that would be hard to replicate.

**Comment by brianmcgee** [comment]
Fixed by https://github.com/numtide/nixos-facter/commit/53cbb6b281c3973faa3c05d1a5a9f957e2cc8187
