### ISSUE TITLE
Put all "unknown" devices that are connected via USB into "usb" instead of "unknown"

### ISSUE THREAD

**Issue by Mic92** [numtide/nixos-facter#136]
That's more intuitive. Currently I have write modules to look both in unknown and usb.

https://github.com/Mic92/dotfiles/blob/b8db102dab16013d48af91bb674ccd1160444e0f/machines/turingmachine/facter.json#L3929

**Comment by brianmcgee** [comment]
I can have a look later this week

**Comment by Mic92** [comment]
We should probably do the same for PCI devices.

**Comment by brianmcgee** [comment]
Ok, it looks like the hardware class is a composite field which can encode multiple hardware classes. In the textual output of hwinfo there's a `HW Class List` 

```
69: USB 00.1: 0000 Unclassified device
  [Created at usb.122]
  Unique ID: JRd1.nXPV_d5LjE5
  Old Unique ID: FrNE.6cEYkEA3jA6
  Parent ID: Uc5H.lRoCB54l1cE
  SysFS ID: /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:08:00.1/usb1/1-4/1-4.3/1-4.3:1.1
  SysFS BusID: 1-4.3:1.1
  Hardware Class: unknown
  HW Class List: usb
  Model: "Yubico.com Yubikey 4/5 OTP+U2F+CCID"
  Hotplug: USB
  Vendor: usb 0x1050 "Yubico.com"
  Device: usb 0x0407 "Yubikey 4/5 OTP+U2F+CCID"
  Revision: "5.43"
  Driver: "usbhid"
  Driver Modules: "usbhid"
  Main Driver Module: "usbhid"
  Speed: 12 Mbps
  Module Alias: "usb:v1050p0407d0543dc00dsc00dp00ic03isc00ip00in01"
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #87 (Hub)
```

In light of this, I need to review how we interpret hw class and also review how I made changes to it for webcam support.
