### ISSUE TITLE
Serialise vendor and device ids as hex

### ISSUE THREAD

**Issue by brianmcgee** [numtide/nixos-facter#141]
See the conversation here https://github.com/numtide/nixos-facter-modules/pull/58

This would be a potential breaking change to the report format.

**Comment by Mic92** [comment]
To make migration easier we could deprecate the old value and introduce a new field?
Otherwise it could be potentially hard to update both the report and the modules in lock step in all cases.

**Comment by Mic92** [comment]
After modules are migrated we bump the version number and remove the field again. This would be an exercise how to upgrade the schema before we have many users.
