### ISSUE TITLE
Set up Mkdocs and publication CI job

### ISSUE THREAD

**Issue by osslate** [numtide/nixos-facter#22]
@brianmcgee do we have a Netlify/Vercel/similar set up for publishing docs, or is GitHub Pages the way to go?

**Comment by brianmcgee** [comment]
Github Pages is how we usually deploy docs.

**Comment by zimbatm** [comment]
Related, we have a bit of an extension of mkdocs over here: https://github.com/numtide/mkdocs-numtide

**Comment by brianmcgee** [comment]
Closing this as we've moved to a separate docs repository
