### ISSUE TITLE
Reports gets very large

### ISSUE THREAD

**Issue by Mic92** [numtide/nixos-facter#63]
I have reports here that are 50k lines (100KB): https://github.com/TUM-DSE/doctor-cluster-config/blob/a33464567de498f534921c6b69329e4068f7aa8d/hosts/xavier-factor.json

CPUs seem be a substantial port of it. We don't need an entry for each CPU core but instead just one per CPU socket. Cache objects are also not interesting just now.

**Comment by Mic92** [comment]
There is also quite a bit redundancy between "detail" structs and the normal struct.
Why not just merge "detail" into the base struct?

**Comment by brianmcgee** [comment]
This was a first pass at modeling, sticking to what `hwinfo` provided. I agree though, we can merge the detail info into the parent hardware device model.
